# Generated by Django 5.0.3 on 2026-08-31 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'marketplace_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductoORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, default='', max_length=500)),
                ('resource_type', models.CharField(choices=[('herramienta_digital', 'Herramienta Digital'), ('recurso_educativo', 'Recurso Educativo'), ('servicio', 'Servicio Institucional'), ('capacitacion', 'Capacitación / Taller'), ('otro', 'Otro')], default='herramienta_digital', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('external_url', models.URLField(blank=True, default='', max_length=1000)),
                ('section', models.CharField(choices=[('destacadas', 'Soluciones Destacadas'), ('mes', 'Innovaciones del Mes'), ('recomendadas', 'Colección Recomendada'), ('general', 'Catálogo General')], default='destacadas', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='productos.categoriaorm')),
            ],
            options={
                'verbose_name': 'Producto / Recurso',
                'verbose_name_plural': 'Productos / Recursos',
                'db_table': 'marketplace_product',
                'ordering': ['-created_at'],
            },
        ),
    ]
